// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhsgIN23lRq2UQCLs290BOSWA1LIqWRGA',
    appId: '1:1001855471334:web:8f5f331ba771e2af3ab527',
    messagingSenderId: '1001855471334',
    projectId: 'yemey-siarot',
    authDomain: 'yemey-siarot.firebaseapp.com',
    databaseURL: 'https://yemey-siarot.firebaseio.com',
    storageBucket: 'yemey-siarot.appspot.com',
    measurementId: 'G-CYJEVWCDNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBylmGDFvW4cB7_TXsbiRj2ATiVkq6cws8',
    appId: '1:1001855471334:android:ca9902b5c7c5fc813ab527',
    messagingSenderId: '1001855471334',
    projectId: 'yemey-siarot',
    databaseURL: 'https://yemey-siarot.firebaseio.com',
    storageBucket: 'yemey-siarot.appspot.com',
  );
}
